Repository APP-Android2/FinalProject-ShoppingMallService-team5, pull requests merged in 2024-04, with the labels that each got.

#11 [#10] 버튼 디자인 추가 및 코드 수정
  MungNolZa/.idea/deploymentTargetDropDown.xml
  MungNolZa/app/src/main/AndroidManifest.xml
  MungNolZa/app/src/main/res/drawable/shared_button_design.xml
  MungNolZa/app/src/main/res/layout/activity_join.xml
  MungNolZa/app/src/main/res/layout/activity_login.xml
  MungNolZa/app/src/main/res/layout/activity_on_boarding.xml
  MungNolZa/app/src/main/res/layout/fragment_input_pet_profile.xml
  MungNolZa/app/src/main/res/layout/fragment_on_boarding2.xml
  MungNolZa/app/src/main/res/layout/fragment_on_boarding3.xml
  MungNolZa/app/src/main/res/layout/permission_dialog.xml
  MungNolZa/app/src/main/res/values/dimens.xml
  MungNolZa/app/src/main/res/values/strings.xml
  MungNolZa/app/src/main/res/values/themes.xml
Labels: UI, 리팩토링

#39 [#36] feature 메인 화면 자유 게시판
  MungNolZa/app/src/main/AndroidManifest.xml
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/BoardAddUerInfoModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/BoardModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/UserModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/FreeBoardRepository.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/FreeBoardRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/UserRepository.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/UserRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/freeboard/viewmodel/FreeBoardViewModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/MainActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/adapter/FreeBoardAdapter.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/FreeBoardFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/HomeFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/MainChatFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/adapter/BoardAdapter.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/adapter/ChattingAdapter.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/viewmodel/MainViewModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/viewmodel/MainViewModelFactory.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/viewmodel/TestViewModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/util/BoardUtil.kt
  MungNolZa/app/src/main/res/layout/fragment_free_board.xml
  MungNolZa/app/src/main/res/layout/fragment_home.xml
  MungNolZa/app/src/main/res/layout/fragment_main_chat.xml
  MungNolZa/app/src/main/res/layout/row_free_board.xml
  MungNolZa/app/src/main/res/menu/menu_free_board.xml
  MungNolZa/app/src/main/res/values/colors.xml
  MungNolZa/app/src/main/res/values/dimens.xml
  MungNolZa/app/src/main/res/values/strings.xml
Labels: 기능

#45 [#33] Home 화면 UI 개발 완료
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/PetsitterReviewModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/adapter/BoardAdapter.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/adapter/HomeReviewAdapter.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/HomeFragment.kt
  MungNolZa/app/src/main/res/drawable/petsitter_main.png
  MungNolZa/app/src/main/res/layout/activity_main.xml
  MungNolZa/app/src/main/res/layout/fragment_home.xml
  MungNolZa/app/src/main/res/layout/row_review_preview.xml
  MungNolZa/app/src/main/res/values/colors.xml
  MungNolZa/app/src/main/res/values/dimens.xml
  MungNolZa/app/src/main/res/values/strings.xml
Labels: UI

#47 [#46] 다음 주소 API 연동
  MungNolZa/app/src/main/AndroidManifest.xml
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/activity/AddressActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/util/Tools.kt
  MungNolZa/app/src/main/res/layout/activity_address.xml
Labels: 기능

#50 [#34] feature 예약 기능 개발 1단계 - 서비스 선택
  MungNolZa/app/build.gradle.kts
  MungNolZa/app/src/main/AndroidManifest.xml
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/datasource/MainDataStore.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/PetImgModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/PetInfo.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/PetModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/freeboard/FreeBoardRepository.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/freeboard/FreeBoardRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/pet/PetRepository.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/pet/PetRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/user/UserRepository.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/user/UserRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/AppointmentActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/NoPetActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/adapter/MyPetAdapter.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/AppointmentMainFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/AppointmentUserAddressFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/vm/AppointmentViewModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/vm/AppointmentViewModelFactory.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/HomeFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/viewmodel/MainViewModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/viewmodel/MainViewModelFactory.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/util/App.kt
  MungNolZa/app/src/main/res/layout/activity_no_pet.xml
  MungNolZa/app/src/main/res/layout/appointment_pet_select_item.xml
  MungNolZa/app/src/main/res/layout/fragment_appointment_main.xml
  MungNolZa/app/src/main/res/layout/fragment_appointment_user_address.xml
  MungNolZa/app/src/main/res/layout/fragment_home.xml
  MungNolZa/app/src/main/res/values/dimens.xml
Labels: 기능

#52 [#51] feature 예약 화면 연결
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/AppointmentDogTimeSelection2Fragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/AppointmentDogTimeSelectionFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/AppointmentUserAddressFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/ReservationListOngoingFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/matching_petsitter/fragment/MatchingFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/matching_petsitter/fragment/PaymentFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/matching_petsitter/fragment/ReservationConfirmedFragment.kt
  MungNolZa/app/src/main/res/layout/activity_no_pet.xml
  MungNolZa/app/src/main/res/layout/fragment_matching.xml
  MungNolZa/app/src/main/res/layout/fragment_payment.xml
  MungNolZa/app/src/main/res/layout/fragment_reservation_confirmed.xml
  MungNolZa/app/src/main/res/navigation/nav_appointment_graph.xml
  MungNolZa/app/src/main/res/values/strings.xml
Labels: UI

#54 [#53] bottomNavigation 수정 및 기타 UI 수정
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/HomeFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/ReservationListFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/reservation_list/ReservationListActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/reservation_list/fragment/ReservationListOngoingFragment.kt
  MungNolZa/app/src/main/res/drawable/ic_chat_bubble_24px.xml
  MungNolZa/app/src/main/res/drawable/ic_forum_24px.xml
  MungNolZa/app/src/main/res/drawable/ic_freeboard_24px.xml
  MungNolZa/app/src/main/res/drawable/ic_newspaper_24px.xml
  MungNolZa/app/src/main/res/layout/activity_main.xml
  MungNolZa/app/src/main/res/layout/fragment_home.xml
  MungNolZa/app/src/main/res/layout/fragment_reservation_list.xml
  MungNolZa/app/src/main/res/layout/fragment_reservation_list_ongoing.xml
  MungNolZa/app/src/main/res/layout/row_comment.xml
  MungNolZa/app/src/main/res/menu/menu_bottom_navigation.xml
  MungNolZa/app/src/main/res/navigation/bottom_navigation_graph.xml
Labels: UI

#57 [#56] refactor 펫 정보 데이터 초기화 시점 변경
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/fragment/OnBoardingFragment1.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/fragment/OnBoardingFragment3.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/MainActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/HomeFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/viewmodel/MainViewModel.kt
Labels: 리팩토링

#49 [#48] refactor 코드 리뷰를 적용한 리팩토링
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/BoardAddUerInfoModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/BoardModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/UserModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/freeboard/FreeBoardRepository.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/freeboard/FreeBoardRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/user/UserRepository.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/user/UserRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/adapter/FreeBoardAdapter.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/FreeBoardFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/viewmodel/MainViewModel.kt
Labels: 리팩토링

#60 [#59] feature 메인 화면에서 사용자 데이터 넘기기
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/UserModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/user/UserRepository.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/user/UserRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/FreeBoardFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/viewmodel/MainViewModel.kt
Labels: 기능

#63 [#61] 온보딩 화면 패키지 및 viewmodel 분리
  MungNolZa/app/src/main/AndroidManifest.xml
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/activity/JoinActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/MainActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/FreeBoardFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/HomeFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/vm/MainViewModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/vm/MainViewModelFactory.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/onboarding/OnBoardingActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/onboarding/fragment/OnBoardingFragment1.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/onboarding/fragment/OnBoardingFragment2.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/onboarding/fragment/OnBoardingFragment3.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/onboarding/vm/OnBoardingViewModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/onboarding/vm/OnBoardingViewModelFactory.kt
  MungNolZa/app/src/main/res/layout/fragment_on_boarding1.xml
  MungNolZa/app/src/main/res/layout/fragment_on_boarding2.xml
  MungNolZa/app/src/main/res/layout/fragment_on_boarding3.xml
Labels: 기능, UI, 리팩토링

#65 [#51] feature 예약 화면 연결
  MungNolZa/app/src/main/AndroidManifest.xml
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/user/UserRepository.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/user/UserRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/AppointmentDogTimeSelection2Fragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/AppointmentDogTimeSelectionFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/AppointmentMainFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/AppointmentUserAddressFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/MatchingFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/PaymentFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/PetSitterInfoFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/PetSitterReviewFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/ReservationConfirmedFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/vm/AppointmentViewModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/vm/AppointmentViewModelFactory.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/freeboard/fragment/ShowDetailBoardFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/activity/AddressActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/HomeFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/matching_petsitter/MatchingPetsitterActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/matching_petsitter/fragment/PetSitterInfoFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/matching_petsitter/fragment/PetSitterReviewFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/onboarding/OnBoardingActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/util/Tools.kt
  MungNolZa/app/src/main/res/layout/activity_matching_petsitter.xml
  MungNolZa/app/src/main/res/layout/fragment_appointment_user_address.xml
  MungNolZa/app/src/main/res/layout/fragment_matching.xml
  MungNolZa/app/src/main/res/layout/fragment_payment.xml
  MungNolZa/app/src/main/res/layout/fragment_pet_sitter_info.xml
  MungNolZa/app/src/main/res/layout/fragment_pet_sitter_review.xml
  MungNolZa/app/src/main/res/layout/fragment_reservation_confirmed.xml
  MungNolZa/app/src/main/res/navigation/nav_appointment_graph.xml
  MungNolZa/app/src/main/res/values/dimens.xml
  firebase_search_address/.firebase/hosting.cHVibGlj.cache
  firebase_search_address/firebase.json
  firebase_search_address/public/404.html
  firebase_search_address/public/index.html
Labels: 기능

#77 [#66] feature 캘린더 날짜 선택, 펫시터 매칭, 상세보기 완료
  MungNolZa/app/src/main/AndroidManifest.xml
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/PetSitterModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/PetSitterModelWithImg.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/SelectScheduleModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/petsitter/PetSitterRepository.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/petsitter/PetSitterRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/adapter/PetImgAdapter.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/adapter/PetSitterAdapter.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/AppointmentDogTimeSelectionFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/AppointmentMainFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/AppointmentUserAddressFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/MatchingFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/PetSitterInfoFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/PetSitterReviewFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/vm/AppointmentViewModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/vm/AppointmentViewModelFactory.kt
  MungNolZa/app/src/main/res/drawable/img_thumb.png
  MungNolZa/app/src/main/res/drawable/img_tropy.png
  MungNolZa/app/src/main/res/layout/fragment_appointment_dog_time_selection.xml
  MungNolZa/app/src/main/res/layout/fragment_appointment_main.xml
  MungNolZa/app/src/main/res/layout/fragment_appointment_user_address.xml
  MungNolZa/app/src/main/res/layout/fragment_matching.xml
  MungNolZa/app/src/main/res/layout/fragment_pet_sitter_info.xml
  MungNolZa/app/src/main/res/layout/row_matching.xml
  MungNolZa/app/src/main/res/layout/row_selected_pet.xml
  MungNolZa/app/src/main/res/navigation/nav_appointment_graph.xml
  MungNolZa/app/src/main/res/values/strings.xml
Labels: 기능, UI

#86 [#84] feature 매칭된 펫시터 선택 기능
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ext/FmExt.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ext/TextViewExt.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/CareServiceModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/WalkServiceModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/reservation/ReservationRepository.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/reservation/ReservationRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/adapter/PetSitterAdapter.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/AppointmentMainFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/MatchingFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/PaymentFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/vm/AppointmentViewModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/vm/AppointmentViewModelFactory.kt
  MungNolZa/app/src/main/res/layout/fragment_matching.xml
  MungNolZa/app/src/main/res/layout/fragment_payment.xml
  MungNolZa/app/src/main/res/layout/row_matching.xml
  MungNolZa/app/src/main/res/navigation/nav_appointment_graph.xml
Labels: 기능

#90 [#89] refactor 코드 리뷰 적용 리팩토링 및 기타 버그 수정
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/BoardModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/CareServiceModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/PetModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/PetSitterModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/SelectScheduleModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/UserModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/WalkServiceModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/AppointmentDogTimeSelection2Fragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/AppointmentDogTimeSelectionFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/AppointmentMainFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/AppointmentUserAddressFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/MatchingFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/PaymentFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/PetSitterInfoFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/ReservationConfirmedFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/FreeBoardFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/HomeFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/ReservationListFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/onboarding/fragment/OnBoardingFragment1.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/onboarding/fragment/OnBoardingFragment2.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/onboarding/fragment/OnBoardingFragment3.kt
  MungNolZa/app/src/main/res/layout/fragment_appointment_dog_time_selection.xml
  MungNolZa/app/src/main/res/layout/fragment_appointment_dog_time_selection2.xml
  MungNolZa/app/src/main/res/layout/fragment_matching.xml
  MungNolZa/app/src/main/res/layout/fragment_payment.xml
Labels: 리팩토링

#92 [#91] feature 최종 예약 완료 구현
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/MatchingFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/PaymentFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/ReservationConfirmedFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/dialog/PositiveCustomDialog.kt
  MungNolZa/app/src/main/res/layout/fragment_payment.xml
  MungNolZa/app/src/main/res/layout/fragment_reservation_confirmed.xml
  MungNolZa/app/src/main/res/navigation/nav_appointment_graph.xml
Labels: 기능, UI

#95 [#89] Repository Method WithContext(Dispathcer.IO) 추가
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/freeboard/FreeBoardRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/pet/PetRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/petsitter/PetSitterRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/user/UserRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/viewmodel/MainViewModel.kt
Labels: 기능

#97 [#96] 카카오 로그인 기능
  MungNolZa/app/build.gradle.kts
  MungNolZa/app/src/main/AndroidManifest.xml
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/user/UserRepository.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/user/UserRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/activity/JoinActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/activity/LoginActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/activity/StartActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/vm/JoinViewModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/vm/JoinViewModelFactory.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/vm/LoginViewModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/vm/LoginViewModelFactory.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/vm/StartViewModel.kt
  MungNolZa/app/src/main/res/layout/activity_join.xml
  MungNolZa/app/src/main/res/layout/activity_login.xml
  MungNolZa/app/src/main/res/values/strings.xml
  MungNolZa/settings.gradle.kts
Labels: 기능

#103 [#102] 네이버 지도 api 연결 및 실시간 위치 트래킹
  .gitignore
  MungNolZa/app/build.gradle.kts
  MungNolZa/app/src/main/AndroidManifest.xml
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/Location.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/model/LocationRequestModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/location/LocationRepository.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/location/LocationRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/TestActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/realtime_location/RealtimeLocationActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/realtime_location/vm/LocationViewModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/realtime_location/vm/LocationViewModelFactory.kt
  MungNolZa/app/src/main/res/drawable/ic_send_24px.xml
  MungNolZa/app/src/main/res/layout/activity_realtime_location.xml
  MungNolZa/app/src/main/res/layout/bottomsheet_chatting.xml
  MungNolZa/app/src/main/res/values/client.xml
  MungNolZa/app/src/main/res/values/colors.xml
  MungNolZa/app/src/main/res/values/dimens.xml
  MungNolZa/app/src/main/res/values/themes.xml
  MungNolZa/settings.gradle.kts
Labels: 기능

#108 [#105] room database 추가, Repository Room Dependency 추가
  MungNolZa/app/build.gradle.kts
  MungNolZa/app/schemas/kr.co.lion.mungnolza.datasource.local.MainDataBase/1.json
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/datasource/local/MainDataBase.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/datasource/local/MyPetDao.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/datasource/local/MyPetEntity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/pet/PetRepository.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/pet/PetRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/activity/LoginActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/activity/StartActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/vm/LoginViewModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/vm/LoginViewModelFactory.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/vm/StartViewModelFactory.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/MainActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/FreeBoardFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/HomeFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/vm/MainViewModelFactory.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/petsitter_main/fragment/PetsitterFreeBoardFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/util/App.kt
Labels: 기능

#110 [#109] 반려동물 정보 room에 저장
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/pet/PetRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/activity/LoginActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/activity/StartActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/vm/LoginViewModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/vm/StartViewModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/MainActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/vm/MainViewModel.kt
Labels: 기능

#111 네이버 API를 사용한 실시간 트래킹
  MungNolZa/app/src/main/AndroidManifest.xml
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/TestActivity.kt
  MungNolZa/app/src/main/res/layout/activity_test.xml
  MungNolZa/app/src/main/res/values/strings.xml
Labels: 기능

#115 [#114] 파이어베이스 의존성 주입 방식 변경
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/freeboard/FreeBoardRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/location/LocationRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/pet/PetRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/petsitter/PetSitterRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/reservation/ReservationRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/user/UserRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/TestActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/vm/AppointmentViewModelFactory.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/freeboard/fragment/AddBoardFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/freeboard/fragment/ShowDetailBoardFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/vm/JoinViewModelFactory.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/vm/LoginViewModelFactory.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/vm/StartViewModelFactory.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/vm/MainViewModelFactory.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/realtime_location/vm/LocationViewModelFactory.kt
Labels: 기능

#116 [#75] 프로필 화면 구현 재업로드
  MungNolZa/app/src/main/AndroidManifest.xml
Labels: UI

#119 [#118] 코드 리팩토링
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/petsitter/PetSitterRepository.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/petsitter/PetSitterRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/AppointmentMainFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/AppointmentUserAddressFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/MatchingFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/PaymentFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/PetSitterInfoFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/vm/AppointmentViewModel.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/intro/activity/StartActivity.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/FreeBoardFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/fragment/HomeFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/petsitter_main/fragment/PetsitterFreeBoardFragment.kt
  MungNolZa/app/src/main/res/layout/fragment_appointment_user_address.xml
Labels: 기능, 리팩토링

#121 [#120] 예약 날짜 명세 layout chip 추가
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/adapter/DateAdapter.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/MatchingFragment.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/appointment/fragment/ReservationConfirmedFragment.kt
  MungNolZa/app/src/main/res/drawable/baseline_calendar_month_24.xml
  MungNolZa/app/src/main/res/layout/fragment_matching.xml
  MungNolZa/app/src/main/res/layout/fragment_payment.xml
  MungNolZa/app/src/main/res/layout/fragment_reservation_confirmed.xml
  MungNolZa/app/src/main/res/layout/row_date.xml
Labels: 기능

#124 [#123] 게시판 정보 가져오기 오류
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/freeboard/FreeBoardRepository.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/freeboard/FreeBoardRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/user/UserRepository.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/repository/user/UserRepositoryImpl.kt
  MungNolZa/app/src/main/java/kr/co/lion/mungnolza/ui/main/vm/MainViewModel.kt
Labels: 버그
